### ISSUE TITLE
generating data fails

### ISSUE THREAD

**Issue by hansbogert** [databricks/spark-sql-perf#13]
The initial generation of data seems to fail:

``` 
15/09/07 23:54:23 INFO EventLoggingListener: Logging events to file:/tmp/spark-events/1/20150907-235419-84120842-5050-11875-0000

SELECT
 ss_sold_date_sk,ss_sold_time_sk,ss_item_sk,ss_customer_sk,ss_cdemo_sk,ss_hdemo_sk,ss_addr_sk,ss_store_sk,ss_promo_sk,ss_ticket_number,ss_quantity,ss_wholesale_cost,ss_list_price,ss_sales_price,ss_ext_discount_amt,ss_ext_sales_price,ss_ext_wholesale_cost,ss_ext_list_price,ss_ext_tax,ss_coupon_amt,ss_net_paid,ss_net_paid_inc_tax,ss_net_profit
FROM
  store_sales_text
DISTRIBUTE BY
  ss_sold_date_sk
            Exception in thread "main" java.lang.RuntimeException: [6.12] failure: \`\`union'' expected but `by' found

DISTRIBUTE BY

                        ^
        at scala.sys.package$.error(package.scala:27)
        at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:36)
        at org.apache.spark.sql.catalyst.DefaultParserDialect.parse(ParserDialect.scala:67)
        at org.apache.spark.sql.SQLContext$$anonfun$3.apply(SQLContext.scala:169)
        at org.apache.spark.sql.SQLContext$$anonfun$3.apply(SQLContext.scala:169)
        at org.apache.spark.sql.SparkSQLParser$$anonfun$org$apache$spark$sql$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:115)
        at org.apache.spark.sql.SparkSQLParser$$anonfun$org$apache$spark$sql$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:114)
        at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
        at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
        at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Failure.append(Parsers.scala:202)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
        at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
        at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890)
        at scala.util.parsing.combinator.PackratParsers$$anon$1.apply(PackratParsers.scala:110)
        at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:34)
        at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:166)
        at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:166)
        at org.apache.spark.sql.execution.datasources.DDLParser.parse(DDLParser.scala:42)
        at org.apache.spark.sql.SQLContext.parseSql(SQLContext.scala:189)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:719)
        at com.databricks.spark.sql.perf.tpcds.Tables$Table.genData(Tables.scala:141)
        at com.databricks.spark.sql.perf.tpcds.Tables$$anonfun$genData$2.apply(Tables.scala:204)
        at com.databricks.spark.sql.perf.tpcds.Tables$$anonfun$genData$2.apply(Tables.scala:202)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at com.databricks.spark.sql.perf.tpcds.Tables.genData(Tables.scala:202)
        at SimpleApp$.tpc(submitApp.scala:110)
        at SimpleApp$.main(submitApp.scala:147)
        at SimpleApp.main(submitApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
15/09/07 23:54:26 INFO SparkContext: Invoking stop() from shutdown hook
15/09/07 23:54:26 INFO SparkUI: Stopped Spark web UI at http://10.141.3.5:4040
15/09/07 23:54:26 INFO DAGScheduler: Stopping DAGScheduler
I0907 23:54:26.484743 12297 sched.cpp:1286] Asked to stop the driver
I0907 23:54:26.484998 12275 sched.cpp:752] Stopping framework '20150907-235419-84120842-5050-11875-0000'
15/09/07 23:54:26 INFO MesosSchedulerBackend: driver.run() returned with code DRIVER_STOPPED
15/09/07 23:54:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
15/09/07 23:54:26 INFO MemoryStore: MemoryStore cleared
15/09/07 23:54:26 INFO BlockManager: BlockManager stopped
15/09/07 23:54:26 INFO BlockManagerMaster: BlockManagerMaster stopped
15/09/07 23:54:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
15/09/07 23:54:26 INFO SparkContext: Successfully stopped SparkContext
15/09/07 23:54:26 INFO ShutdownHookManager: Shutdown hook called
15/09/07 23:54:26 INFO ShutdownHookManager: Deleting directory /local/vdbogert/tmp1/spark-d25f80c9-46e9-45e9-a92a-bd29e766a1a7
Reservation 3423559 cancelled
```

**Comment by hansbogert** [comment]
Needed HiveContext.
