### ISSUE TITLE
sbt.ResolveException: unresolved dependency: org.apache.spark#spark-sql_2.10;2.0.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by shujamughal** [databricks/spark-sql-perf#84]
Hi
I am getting following exception while running it. please help. Thanks

shuja@shuja:~/Desktop/data/spark-sql-perf-master$ bin/run --benchmark DatasetPerformance
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[info] Loading project definition from /home/shuja/Desktop/data/spark-sql-perf-master/project
Missing bintray credentials /home/shuja/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to spark-sql-perf (in build file:/home/shuja/Desktop/data/spark-sql-perf-master/)
[warn] Credentials file /home/shuja/.bintray/.credentials does not exist
[info] Updating {file:/home/shuja/Desktop/data/spark-sql-perf-master/}spark-sql-perf-master...
[info] Resolving org.apache.spark#spark-sql_2.10;2.0.0-SNAPSHOT ...
[warn] 	module not found: org.apache.spark#spark-sql_2.10;2.0.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/shuja/.ivy2/local/org.apache.spark/spark-sql_2.10/2.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.10/2.0.0-SNAPSHOT/spark-sql_2.10-2.0.0-SNAPSHOT.pom
[warn] ==== Spark Packages Repo: tried
[warn]   https://dl.bintray.com/spark-packages/maven/org/apache/spark/spark-sql_2.10/2.0.0-SNAPSHOT/spark-sql_2.10-2.0.0-SNAPSHOT.pom
[warn] ==== apache-snapshots: tried
[warn]   https://repository.apache.org/snapshots/org/apache/spark/spark-sql_2.10/2.0.0-SNAPSHOT/spark-sql_2.10-2.0.0-SNAPSHOT.pom
[info] Resolving org.apache.spark#spark-hive_2.10;2.0.0-SNAPSHOT ...
[warn] 	module not found: org.apache.spark#spark-hive_2.10;2.0.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/shuja/.ivy2/local/org.apache.spark/spark-hive_2.10/2.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/spark/spark-hive_2.10/2.0.0-SNAPSHOT/spark-hive_2.10-2.0.0-SNAPSHOT.pom
[warn] ==== Spark Packages Repo: tried
[warn]   https://dl.bintray.com/spark-packages/maven/org/apache/spark/spark-hive_2.10/2.0.0-SNAPSHOT/spark-hive_2.10-2.0.0-SNAPSHOT.pom
[warn] ==== apache-snapshots: tried
[warn]   https://repository.apache.org/snapshots/org/apache/spark/spark-hive_2.10/2.0.0-SNAPSHOT/spark-hive_2.10-2.0.0-SNAPSHOT.pom
[info] Resolving org.apache.spark#spark-mllib_2.10;2.0.0-SNAPSHOT ...
[warn] 	module not found: org.apache.spark#spark-mllib_2.10;2.0.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/shuja/.ivy2/local/org.apache.spark/spark-mllib_2.10/2.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/spark/spark-mllib_2.10/2.0.0-SNAPSHOT/spark-mllib_2.10-2.0.0-SNAPSHOT.pom
[warn] ==== Spark Packages Repo: tried
[warn]   https://dl.bintray.com/spark-packages/maven/org/apache/spark/spark-mllib_2.10/2.0.0-SNAPSHOT/spark-mllib_2.10-2.0.0-SNAPSHOT.pom
[warn] ==== apache-snapshots: tried
[warn]   https://repository.apache.org/snapshots/org/apache/spark/spark-mllib_2.10/2.0.0-SNAPSHOT/spark-mllib_2.10-2.0.0-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.spark#spark-sql_2.10;2.0.0-SNAPSHOT: not found
[warn] 	:: org.apache.spark#spark-hive_2.10;2.0.0-SNAPSHOT: not found
[warn] 	:: org.apache.spark#spark-mllib_2.10;2.0.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.apache.spark:spark-sql_2.10:2.0.0-SNAPSHOT ((sbtsparkpackage.SparkPackagePlugin) SparkPackagePlugin.scala#L186)
[warn] 		  +- com.databricks:spark-sql-perf_2.10:0.4.10-SNAPSHOT
[warn] 		org.apache.spark:spark-hive_2.10:2.0.0-SNAPSHOT ((sbtsparkpackage.SparkPackagePlugin) SparkPackagePlugin.scala#L186)
[warn] 		  +- com.databricks:spark-sql-perf_2.10:0.4.10-SNAPSHOT
[warn] 		org.apache.spark:spark-mllib_2.10:2.0.0-SNAPSHOT ((sbtsparkpackage.SparkPackagePlugin) SparkPackagePlugin.scala#L186)
[warn] 		  +- com.databricks:spark-sql-perf_2.10:0.4.10-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.apache.spark#spark-sql_2.10;2.0.0-SNAPSHOT: not found
unresolved dependency: org.apache.spark#spark-hive_2.10;2.0.0-SNAPSHOT: not found
unresolved dependency: org.apache.spark#spark-mllib_2.10;2.0.0-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-sql_2.10;2.0.0-SNAPSHOT: not found
[error] unresolved dependency: org.apache.spark#spark-hive_2.10;2.0.0-SNAPSHOT: not found
[error] unresolved dependency: org.apache.spark#spark-mllib_2.10;2.0.0-SNAPSHOT: not found
[error] Total time: 10 s, completed Aug 17, 2016 5:19:11 PM

**Comment by JoshRosen** [comment]
We need to update the build now that 2.0.0 has been released, since the old snapshot repository isn't available. I'll submit a PR now to fix this.
