### ISSUE TITLE
java.lang.RuntimeException: [1.1] failure: ``with'' expected but identifier CREATE found

### ISSUE THREAD

**Issue by wangli86** [databricks/spark-sql-perf#95]
hi:
I am facing below issues, when I am trying to run this code. For this command
tables.createExternalTables("file:///home/tpctest/", "parquet", "mydata", false) 
java.lang.RuntimeException: [1.1] failure: ``with'' expected but identifier CREATE found

CREATE DATABASE IF NOT EXISTS mydata
^
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:36)
	at org.apache.spark.sql.catalyst.DefaultParserDialect.parse(ParserDialect.scala:67)
	at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:211)
	at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:211)
	at org.apache.spark.sql.execution.SparkSQLParser$$anonfun$org$apache$spark$sql$execution$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:114)
	at org.apache.spark.sql.execution.SparkSQLParser$$anonfun$org$apache$spark$sql$execution$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:113)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
      ..............

I used spark-sql-perf-0.2.4 ,scala-2.10.5 spark-1.6.1;  
but this commend:
tables.createTemporaryTables("file:///home/wl/tpctest/", "parquet") has no problem,
can you help me resove this problem?
and tpcds.createResultsTable() commend has the same with tables.createExternalTables()

**Comment by YuanGunGun** [comment]
I met the same problem

**Comment by gonzalobd** [comment]
having the same issue

**Comment by msolano00** [comment]
Any updates on this issue?

**Comment by Mr-San** [comment]
You need use HiveContext rather than SQLContext
[using-hivecontext-in-maven-project](https://stackoverflow.com/questions/28931166/using-hivecontext-in-maven-project)
[spark-submit-sql-context-create-statement-does-not-work](https://stackoverflow.com/questions/32056829/spark-submit-sql-context-create-statement-does-not-work)
